In [2]:
import numpy as np
import tensorflow as tf


In [4]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
#d = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]],[[19,20],[21,22],[23,24]]])
#d

In [12]:
e = np.random.randn(3,3)
#e = np.random.randn(2,3)
e

array([[-1.03114966,  1.24939065, -0.25591672],
       [ 1.33408256, -0.46227237, -0.18018944],
       [ 0.53365836,  1.40147975,  1.24767028]])

In [20]:
w1 = np.random.rand(3,3)
print(w1)
w2 = np.random.rand(2,3)
print(w2)
x = np.array([22,35,86])
print(np.dot(w1,x))
y1 = np.dot(w2, (np.dot(w1,x)))
y1

[[0.09991129 0.01258806 0.88644175]
 [0.82151224 0.74523432 0.31342734]
 [0.93322707 0.31966501 0.4665637 ]]
[[0.03665719 0.15965093 0.73366593]
 [0.03031836 0.94533308 0.77093442]]
[78.87262065 71.1112218  71.84374939]


array([ 66.95353342, 125.00189794])

In [24]:
rank0_tensor = tf.constant(4)
print(rank0_tensor)

tf.Tensor([4], shape=(1,), dtype=int32)


In [26]:
rank1_tensor = tf.constant([1.0 ,2.0 ,3.0])
print(rank1_tensor)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [31]:
rank2_tensor = tf.constant([[1.0 ,2.0],[3,4.0],[5.0, 6.0]])
print(rank2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)


In [33]:
a = tf.constant([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
print(a)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]], shape=(4, 4), dtype=int32)


In [35]:
x = tf.constant(np.random.randn(4,5,6))
print(x)

tf.Tensor(
[[[-1.07875818 -0.61564944 -0.72643782 -0.72592727  2.32081523
   -0.30924841]
  [-0.76721888 -0.87692558 -0.47833473  0.37856384  0.6734567
    0.2755614 ]
  [-0.20955979  0.16439451  0.51187105 -0.155933    1.24444786
   -0.1912806 ]
  [-0.10977367 -1.53752748  0.40502606 -1.48304009 -0.06713576
    0.50513666]
  [-0.84814836 -1.88465659 -0.79988916  0.61417512  1.9395233
   -0.06321106]]

 [[-1.9195088   1.15051719  1.84167091  0.2712267  -0.63639143
   -0.15097267]
  [ 0.28943822  0.47681163  0.37582997 -0.11745876  0.61484491
    1.05490627]
  [ 0.77306621  0.01720898  0.44759232  1.23280743 -0.48274185
    0.34938476]
  [ 0.98941019 -0.63104298  0.94391795 -1.35128111  0.17365266
   -0.72434418]
  [-0.59965139 -1.18872497 -1.28269144  0.36337729 -1.02549695
    0.32070463]]

 [[ 0.649743   -0.01844819  0.49275356 -0.72974283  0.04090975
   -0.12122152]
  [ 0.49330051  0.32884049  0.23563389  0.97633717  1.04634673
   -1.02559186]
  [-0.09274814 -0.01823963  1.2276722  

In [38]:
a = tf.constant([
    [1,2],
    [3,4]
])
b = tf.constant([
    [1,2],
    [1,2]
])
print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a,b), "\n")

tf.Tensor(
[[2 4]
 [4 6]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 4]
 [3 8]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 3  6]
 [ 7 14]], shape=(2, 2), dtype=int32) 



In [39]:
var_x = tf.Variable(tf.constant([[1],[2],[3]]))
print(var_x)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[1],
       [2],
       [3]])>


In [40]:
print(tf.debugging.set_log_device_placement)


<function set_log_device_placement at 0x000001F1C64DE318>


In [59]:
my_tensor = tf.constant([[0,0],[0,11]])
my_variable = tf.Variable(my_tensor)
print(my_variable)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 0,  0],
       [ 0, 11]])>


In [60]:
print(tf.convert_to_tensor(my_variable))


tf.Tensor(
[[ 0  0]
 [ 0 11]], shape=(2, 2), dtype=int32)


In [61]:
print(tf.argmax(my_tensor))

tf.Tensor([0 1], shape=(2,), dtype=int64)
